### ISSUE TITLE
Add cycloserine resistance results to LIMS report

### ISSUE THREAD

**Issue by emily-smith1** [theiagen/tbp-parser#9]
### :pushpin: Explain the Request

Add cycloserine resistance results to LIMS report.

### :books: Context

Cycloserine resistance-conferring mutations appear in the laboratorian report, but not in the LIMS report. TB controllers would like to see this added to the LIMS report. However, this should be optional as not to interfere with any existing validations or ongoing work by other laboratories.

### :chart_with_upwards_trend: Desired Behavior

Optional workflow input that allows user to specify that cycloserine resistance results should be included in LIMS report. 

### :information_source: Additional Information

NA

**Comment by sage-wright** [comment]
addressed with v1.5.7+
